EXT=.dll
SHARED=-shared

FORTRAN_LIB= -lgfortran
BLAS_LIB= "/c/local/Numeric/lib/libgoto2_dll.lib" $(FORTRAN_LIB)
LAPACK_LIB= "/c/local/Numeric/lib/lapack.a" $(BLAS_LIB)
ARPACK_LIB= /c/local/Numeric/lib/libarpack.a $(LAPACK_LIB) 
BLZPACK_LIB= /c/local/Numeric/lib/libblzpack.a $(LAPACK_LIB) 

LUA_LIB= -L"/c/Program Files (x86)/Lua/5.1/lib/" -L"/c/Program Files/Lua/5.1/lib/" -llua5.1
LUA_INC= -I"/c/Program Files/Lua/5.1/include" -I"/c/Program Files (x86)/Lua/5.1/include"

UMFPACK_LIB=/c/local/Numeric/lib/libumfpack.a\
       /c/local/Numeric/lib/libcholmod.a\
       /c/local/Numeric/lib/libccolamd.a\
       /c/local/Numeric/lib/libcolamd.a\
       /c/local/Numeric/lib/libcamd.a\
       /c/local/Numeric/lib/libamd.a\
       /c/local/Numeric/lib/libmetis.a\
			 $(BLAS_LIB)
UMFPACK_INC= -I /c/local/Numeric/include  

MA57_LIB= /c/local/Numeric/lib/libma57.a /c/local/Numeric/lib/libfakemetis.a \
       $(BLAS_LIB)

MA47_LIB= /c/local/Numeric/lib/libma47.a $(BLAS_LIB)

GL2_LIB = -lglu32 /mingw/lib/glut32.lib -lopengl32 -lglew32.dll
GL2_INC = -I .

CL_LIB = -L"/c/Program Files (x86)/AMD APP/lib/x86/" -L"/c/Program Files/AMD APP/lib/x86/" -lOpenCL -lopengl32
CL_INC = -I "/c/Program Files (x86)/AMD APP/include" -I "/c/Program Files/AMD APP/include"

GSL_LIB = "/c/local/Numeric/lib/libgsl.a" "/c/local/Numeric/lib/libgoto2.lib"
GSL_INC= -I /c/local/Numeric/include  

